local Games = {
    [2753915549] = "https://raw.githubusercontent.com/xBac0nBl1tzX/BloxFruits/refs/heads/main/newredz.luau", -- Blox Fruits Sea 1
    [4442272183] = "https://raw.githubusercontent.com/xBac0nBl1tzX/BloxFruits/refs/heads/main/newredz.luau", -- Blox Fruits Sea 2
    [7449423635] = "https://raw.githubusercontent.com/xBac0nBl1tzX/BloxFruits/refs/heads/main/newredz.luau", -- Blox Fruits Sea 3
    [10449761463] = "https://raw.githubusercontent.com/yes1nt/yes/refs/heads/main/Trashcan%20Man", -- The Strongest Battlegrounds
    [16732694052] = "https://raw.githubusercontent.com/thantzy/thanhub/refs/heads/main/thanv1", -- Fisch Sea 1
    [72907489978215] = "https://raw.githubusercontent.com/thantzy/thanhub/refs/heads/main/thanv1", -- Fisch Sea 2
    [4620170611] = "https://raw.githubusercontent.com/xBac0nBl1tzX/Break-In/refs/heads/main/Break-In-Story.luau", -- Break In Story
    [606849621] = "https://raw.githubusercontent.com/FlyHubV2/AttackOnZombies/refs/heads/main/AttackOnZombies.lua", -- Zombie Attack Easy Mode
    [2309640633] = "https://raw.githubusercontent.com/FlyHubV2/AttackOnZombies/refs/heads/main/AttackOnZombies.lua", -- Zombie Attack Hard Mode
    [126884695634066] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Grow%20a%20Garden.lua", -- Grow a Garden
    [3623096087] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/main/Muscle%20Legends.lua", -- Muscle Legends
    [8737899170] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/main/PS99.lua", -- PS99 World 1
    [16498369169] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/main/PS99.lua", -- PS99 World 2
    [17503543197] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/main/PS99.lua", -- PS99 World 3
    [18901165922] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/main/Pet%20GO.lua", -- Pet GO
    [116495829188952] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Dead%20Rails.lua", -- Dead Rails
    [70876832253163] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Dead%20Rails.lua", -- Dead Rails 2
    [125723653259639] = "https://raw.githubusercontent.com/triquqd717/main/refs/heads/main/other/DrillDiggingSimulator.lua", -- Drill Digging Simulator
    [87039211657390] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Arise%20Crossover.lua", -- Arise Crossover
    [128336380114944] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Arise%20Crossover.lua", -- Arise Crossover Dungeon
    [116614712661486] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Arise%20Crossover.lua", -- Arise Crossover AFK Reward
    [85896571713843] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Bubble%20Gum%20Simulator%20INFINITY.lua", -- Bubble Gum Simulator INFINITY
    [91867617264223] = "https://raw.githubusercontent.com/AhmadV99/Script-Games/refs/heads/main/Grow%20a%20Garden.lua", -- Grow a Garden Alt
}

return Games
